#!/bin/bash
# WireGuard Server Setup Script for AgentFarm
# Installs WireGuard, generates keys, and sets up DuckDNS integration
#
# Usage:
#   sudo ./wireguard-setup.sh install     # Full installation
#   sudo ./wireguard-setup.sh add-peer    # Add new peer
#   sudo ./wireguard-setup.sh list-peers  # List all peers
#   sudo ./wireguard-setup.sh status      # Show status
#
# See also: docs/WIREGUARD_SETUP.md

set -e

# Configuration
WG_INTERFACE="wg0"
WG_PORT=51820
WG_SUBNET="10.0.0"
WG_SERVER_IP="10.0.0.1/24"
WG_CONFIG="/etc/wireguard/${WG_INTERFACE}.conf"
DUCKDNS_DOMAIN="${DUCKDNS_DOMAIN:-taborsen.duckdns.org}"
DUCKDNS_TOKEN="${DUCKDNS_TOKEN:-}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check if running as root
check_root() {
    if [ "$EUID" -ne 0 ]; then
        log_error "Please run as root: sudo $0 $*"
        exit 1
    fi
}

# Install WireGuard and dependencies
install_wireguard() {
    log_info "Installing WireGuard..."
    apt update
    apt install -y wireguard wireguard-tools qrencode curl

    log_success "WireGuard installed"
}

# Generate server keys if they don't exist
generate_server_keys() {
    if [ -f /etc/wireguard/server_private.key ]; then
        log_warn "Server keys already exist, skipping generation"
        return
    fi

    log_info "Generating server keys..."

    umask 077
    wg genkey > /etc/wireguard/server_private.key
    wg pubkey < /etc/wireguard/server_private.key > /etc/wireguard/server_public.key

    log_success "Server keys generated"
}

# Detect primary network interface
detect_interface() {
    # Find the interface with default route
    ip route | grep default | awk '{print $5}' | head -1
}

# Create initial server config
create_server_config() {
    if [ -f "$WG_CONFIG" ]; then
        log_warn "WireGuard config already exists at $WG_CONFIG"
        log_warn "Back up and remove it to recreate, or use add-peer to add peers"
        return
    fi

    local server_private_key
    server_private_key=$(cat /etc/wireguard/server_private.key)

    local interface
    interface=$(detect_interface)
    if [ -z "$interface" ]; then
        log_error "Could not detect network interface. Please set manually."
        interface="eth0"
    fi

    log_info "Creating server config (interface: $interface)..."

    cat > "$WG_CONFIG" << EOF
# WireGuard Server Configuration
# Generated by wireguard-setup.sh on $(date)
# Interface: $interface

[Interface]
PrivateKey = $server_private_key
Address = $WG_SERVER_IP
ListenPort = $WG_PORT

# Enable IP forwarding and NAT
PostUp = sysctl -w net.ipv4.ip_forward=1
PostUp = iptables -A FORWARD -i %i -j ACCEPT
PostUp = iptables -A FORWARD -o %i -j ACCEPT
PostUp = iptables -t nat -A POSTROUTING -o $interface -j MASQUERADE

PostDown = iptables -D FORWARD -i %i -j ACCEPT
PostDown = iptables -D FORWARD -o %i -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -o $interface -j MASQUERADE

# Peers will be added below
EOF

    chmod 600 "$WG_CONFIG"
    log_success "Server config created at $WG_CONFIG"
}

# Setup DuckDNS update cron
setup_duckdns() {
    if [ -z "$DUCKDNS_TOKEN" ]; then
        log_warn "DUCKDNS_TOKEN not set, skipping DuckDNS setup"
        log_info "Set DUCKDNS_TOKEN environment variable and run again"
        return
    fi

    log_info "Setting up DuckDNS update..."

    local duckdns_script="/etc/wireguard/duckdns-update.sh"

    cat > "$duckdns_script" << EOF
#!/bin/bash
# DuckDNS IP Update Script
curl -s "https://www.duckdns.org/update?domains=${DUCKDNS_DOMAIN%%.*}&token=$DUCKDNS_TOKEN&ip=" > /dev/null
EOF

    chmod +x "$duckdns_script"

    # Add to cron (every 5 minutes)
    local cron_entry="*/5 * * * * $duckdns_script"
    (crontab -l 2>/dev/null | grep -v "$duckdns_script"; echo "$cron_entry") | crontab -

    # Run immediately
    $duckdns_script

    log_success "DuckDNS update configured"
}

# Enable and start WireGuard
enable_wireguard() {
    log_info "Enabling WireGuard..."

    # Enable IP forwarding permanently
    echo "net.ipv4.ip_forward = 1" > /etc/sysctl.d/99-wireguard.conf
    sysctl -p /etc/sysctl.d/99-wireguard.conf

    # Enable and start service
    systemctl enable wg-quick@${WG_INTERFACE}
    systemctl start wg-quick@${WG_INTERFACE}

    log_success "WireGuard enabled and started"
}

# Get next available peer IP
get_next_peer_ip() {
    local max_ip=1  # Start after server (10.0.0.1)

    if [ -f "$WG_CONFIG" ]; then
        # Find existing peer IPs
        while read -r ip; do
            num=${ip##*.}
            num=${num%%/*}
            if [ "$num" -gt "$max_ip" ]; then
                max_ip=$num
            fi
        done < <(grep "AllowedIPs" "$WG_CONFIG" | grep -oE '10\.0\.0\.[0-9]+')
    fi

    echo $((max_ip + 1))
}

# Add a new peer
add_peer() {
    local peer_name="${1:-peer}"

    if [ ! -f "$WG_CONFIG" ]; then
        log_error "Server not configured. Run 'install' first."
        exit 1
    fi

    local next_ip
    next_ip=$(get_next_peer_ip)

    if [ "$next_ip" -gt 254 ]; then
        log_error "No more IPs available in subnet"
        exit 1
    fi

    local peer_ip="${WG_SUBNET}.${next_ip}"
    local peer_dir="/etc/wireguard/peers/${peer_name}"

    log_info "Adding peer: $peer_name ($peer_ip)"

    # Generate peer keys
    mkdir -p "$peer_dir"
    umask 077
    wg genkey > "$peer_dir/private.key"
    wg pubkey < "$peer_dir/private.key" > "$peer_dir/public.key"

    local peer_private_key
    peer_private_key=$(cat "$peer_dir/private.key")
    local peer_public_key
    peer_public_key=$(cat "$peer_dir/public.key")
    local server_public_key
    server_public_key=$(cat /etc/wireguard/server_public.key)

    # Create peer config file
    cat > "$peer_dir/${peer_name}.conf" << EOF
[Interface]
PrivateKey = $peer_private_key
Address = $peer_ip/24
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = $server_public_key
Endpoint = ${DUCKDNS_DOMAIN}:${WG_PORT}
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
EOF

    # Add peer to server config
    cat >> "$WG_CONFIG" << EOF

# Peer: $peer_name (added $(date +%Y-%m-%d))
[Peer]
PublicKey = $peer_public_key
AllowedIPs = $peer_ip/32
EOF

    # Add peer to running interface
    wg set "${WG_INTERFACE}" peer "$peer_public_key" allowed-ips "$peer_ip/32"

    # Generate QR code
    qrencode -t ANSIUTF8 < "$peer_dir/${peer_name}.conf" > "$peer_dir/qr.txt"
    qrencode -o "$peer_dir/qr.png" < "$peer_dir/${peer_name}.conf"

    log_success "Peer added: $peer_name"
    echo ""
    echo "========================================"
    echo "  Peer Configuration: $peer_name"
    echo "  IP Address: $peer_ip"
    echo "========================================"
    echo ""
    echo "Config file: $peer_dir/${peer_name}.conf"
    echo "QR code image: $peer_dir/qr.png"
    echo ""
    echo "Scan this QR code with WireGuard app:"
    echo ""
    cat "$peer_dir/qr.txt"
}

# List all peers
list_peers() {
    echo ""
    echo "========================================"
    echo "  WireGuard Peers"
    echo "========================================"

    if [ ! -d /etc/wireguard/peers ]; then
        echo "No peers configured"
        return
    fi

    for peer_dir in /etc/wireguard/peers/*/; do
        if [ -d "$peer_dir" ]; then
            local peer_name
            peer_name=$(basename "$peer_dir")
            local peer_ip=""

            if [ -f "$peer_dir/${peer_name}.conf" ]; then
                peer_ip=$(grep "Address" "$peer_dir/${peer_name}.conf" | cut -d= -f2 | tr -d ' ')
            fi

            echo "  - $peer_name: $peer_ip"
        fi
    done

    echo ""
    echo "Active connections:"
    wg show "${WG_INTERFACE}" 2>/dev/null || echo "  WireGuard not running"
}

# Show status
show_status() {
    echo ""
    echo "========================================"
    echo "  WireGuard Status"
    echo "========================================"
    echo ""

    if systemctl is-active --quiet "wg-quick@${WG_INTERFACE}"; then
        log_success "Service: Running"
    else
        log_error "Service: Stopped"
    fi

    local server_public_key
    if [ -f /etc/wireguard/server_public.key ]; then
        server_public_key=$(cat /etc/wireguard/server_public.key)
        echo "Public Key: ${server_public_key:0:20}..."
    fi

    echo "Endpoint: ${DUCKDNS_DOMAIN}:${WG_PORT}"
    echo "Config: $WG_CONFIG"
    echo ""

    echo "Interface Details:"
    wg show "${WG_INTERFACE}" 2>/dev/null || echo "  Not running"
    echo ""

    echo "Network:"
    ip addr show "${WG_INTERFACE}" 2>/dev/null || echo "  Interface not found"
}

# Remove a peer
remove_peer() {
    local peer_name="$1"

    if [ -z "$peer_name" ]; then
        log_error "Usage: $0 remove-peer <peer_name>"
        exit 1
    fi

    local peer_dir="/etc/wireguard/peers/${peer_name}"

    if [ ! -d "$peer_dir" ]; then
        log_error "Peer not found: $peer_name"
        exit 1
    fi

    local peer_public_key
    peer_public_key=$(cat "$peer_dir/public.key")

    log_info "Removing peer: $peer_name"

    # Remove from running interface
    wg set "${WG_INTERFACE}" peer "$peer_public_key" remove

    # Remove from config file (find and remove peer block)
    # This is a bit tricky - we need to remove the peer section
    local temp_config
    temp_config=$(mktemp)

    awk -v pubkey="$peer_public_key" '
        /^\[Peer\]/ { in_peer=1; peer_block=$0"\n"; next }
        in_peer && /^PublicKey/ && $0 ~ pubkey { skip_peer=1 }
        in_peer && /^\[/ { in_peer=0; if (!skip_peer) print peer_block; skip_peer=0 }
        in_peer { peer_block=peer_block $0 "\n"; next }
        !in_peer { print }
        END { if (in_peer && !skip_peer) print peer_block }
    ' "$WG_CONFIG" > "$temp_config"

    mv "$temp_config" "$WG_CONFIG"
    chmod 600 "$WG_CONFIG"

    # Remove peer directory
    rm -rf "$peer_dir"

    log_success "Peer removed: $peer_name"
}

# Full installation
full_install() {
    log_info "Starting full WireGuard installation..."
    echo ""

    check_root

    install_wireguard
    generate_server_keys
    create_server_config
    setup_duckdns
    enable_wireguard

    echo ""
    echo "========================================"
    echo "  Installation Complete!"
    echo "========================================"
    echo ""
    echo "Server is running at: ${DUCKDNS_DOMAIN}:${WG_PORT}"
    echo "Add peers with: $0 add-peer <name>"
    echo ""

    show_status
}

# Main
case "$1" in
    install)
        full_install
        ;;
    add-peer)
        check_root
        add_peer "$2"
        ;;
    remove-peer)
        check_root
        remove_peer "$2"
        ;;
    list-peers)
        list_peers
        ;;
    status)
        show_status
        ;;
    *)
        echo "WireGuard Server Setup Script for AgentFarm"
        echo ""
        echo "Usage: $0 <command> [args]"
        echo ""
        echo "Commands:"
        echo "  install       Full server installation"
        echo "  add-peer NAME Add a new peer"
        echo "  remove-peer NAME Remove a peer"
        echo "  list-peers    List all configured peers"
        echo "  status        Show WireGuard status"
        echo ""
        echo "Environment variables:"
        echo "  DUCKDNS_DOMAIN  DuckDNS domain (default: taborsen.duckdns.org)"
        echo "  DUCKDNS_TOKEN   DuckDNS API token (required for DNS updates)"
        echo ""
        exit 1
        ;;
esac
